version: '3.5'

services:
  angular-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - '4200:80'  # Cambiar el puerto 4200 a 80
    volumes:
      - ./:/app
    environment:
      - STYLE=scss
